version: "3.7"

services:
  justification_service:
    container_name: text_justification_service_container
    image: nestjs_service
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 5000:3000
    restart: unless-stopped